/*
 * TRANSLATION FILE (Spanish)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Levantar Objeto";
STR_R3F_LOG_action_heliporter_fait = "Objeto ""%1"" adjunto.";
STR_R3F_LOG_action_heliport_larguer = "Soltar objeto";
STR_R3F_LOG_action_heliport_larguer_fait = "Objeto ""%1"" soltado.";
STR_R3F_LOG_action_heliport_attente = "Enganchando... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "¡Elevacion abortada! Permanezca suspendido durante el enganche.";

STR_R3F_LOG_action_deplacer_objet = "Tomar ""%1""";
STR_R3F_LOG_action_relacher_objet = "Liberar ""%1""";
STR_R3F_LOG_action_aligner_pente = "Ajustar inclinacion";
STR_R3F_LOG_action_aligner_sol = "Ajustar al suelo";
STR_R3F_LOG_action_aligner_horizon = "Ajustar horizontalmente";
STR_R3F_LOG_action_tourner = "Girar izquierda / derecha (teclas X / C)";
STR_R3F_LOG_action_rapprocher = "Acercar/Alejar (teclas F / R)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "¡No puedes subirte a un vehiculo mientras cargas este objeto!";

STR_R3F_LOG_action_charger_deplace = "Cargar en el vehiculo";
STR_R3F_LOG_action_selectionner_objet_charge = "Cargar ""%1"" en...";
STR_R3F_LOG_action_charger_selection = "... cargar en ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Ahora selecciona el destino para ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Cargando en progreso...";
STR_R3F_LOG_action_charger_fait = "El objeto ""%1"" se ha cargado en ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "¡No hay suficiente espacio para este objeto en este vehiculo!";

STR_R3F_LOG_action_remorquer_direct = "Remolcar ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Remolcar el objeto";
STR_R3F_LOG_action_detacher = "Soltar el objeto";
STR_R3F_LOG_action_detacher_fait = "Objeto soltado.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Solo el piloto puede separar este objeto.";

STR_R3F_LOG_action_contenu_vehicule = "Ver el contenido del vehiculo";
STR_R3F_LOG_action_decharger_en_cours = "Descarga en curso...";
STR_R3F_LOG_action_decharger_fait = "El objeto ""%1"" ha sido descargado del vehiculo.";
STR_R3F_LOG_action_decharger_deja_fait = "¡El objeto ya ha sido descargado!";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Una vez liberado, este objeto ya no se podra mover manualmente.<br/>¿Confirma usted la accion?";

STR_R3F_LOG_action_ouvrir_usine = "Abrir fabrica de creacion";
STR_R3F_LOG_action_creer_en_cours = "Creacion en progreso...";
STR_R3F_LOG_action_creer_fait = "El objeto ""%1"" ha sido creado.";
STR_R3F_LOG_action_creer_pas_assez_credits = "La fabrica no tiene suficientes creditos para crear este objeto.";
STR_R3F_LOG_action_revendre_usine_direct = "Enviar de vuelta ""%1"" a la fabrica";
STR_R3F_LOG_action_revendre_usine_deplace = "Enviar de vuelta a la fabrica";
STR_R3F_LOG_action_revendre_usine_selection = "... enviar de vuelta a la fabrica";
STR_R3F_LOG_action_revendre_en_cours = "Enviando de regreso a la fabrica...";
STR_R3F_LOG_action_revendre_fait = "El objeto ""%1"" ha sido enviado de regreso a la fabrica.";
STR_R3F_LOG_action_revendre_decharger_avant = "¡No puede enviarlo de vuelta mientras su contenido de carga no este vacio!";

STR_R3F_LOG_mutex_action_en_cours = "¡La operacion actual no ha terminado!";
STR_R3F_LOG_joueur_dans_objet = "Hay un jugador en el objeto ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "El objeto ""%1"" ya esta en transito!";
STR_R3F_LOG_objet_remorque_en_cours = "Imposible porque el objeto ""%1"" esta remolcando otro objeto!";
STR_R3F_LOG_trop_loin = "Imposible porque el objeto ""%1"" esta demasiado lejos!";

STR_R3F_LOG_dlg_CV_titre = "Contenido del vehiculo";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Cargando: %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "DESCARGAR";
STR_R3F_LOG_dlg_CV_btn_fermer = "CANCELAR";

STR_R3F_LOG_dlg_LO_titre = "Fabrica de creacion";
STR_R3F_LOG_dlg_LO_credits_restants = "Creditos restantes: %1";
STR_R3F_LOG_dlg_LO_btn_creer = "CREAR";
STR_R3F_LOG_dlg_LO_btn_fermer = "CANCELAR";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Propiedades";
STR_R3F_LOG_nom_fonctionnalite_side = "Bando";
STR_R3F_LOG_nom_fonctionnalite_places = "Asiento";
STR_R3F_LOG_nom_fonctionnalite_passif = "Puede ser:";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Movido por jugador";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Levantado";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Remolcado";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Transportado";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "Costo de carga %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Puede:";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Levantar";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Remolcar";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Transporte";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "carga maxima %1";

STR_R3F_LOG_deverrouillage_en_cours = "Desbloquear... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "¡Desbloqueo cancelado! Mantenga el objetivo del objeto durante la cuenta regresiva.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objeto desbloqueado.";
STR_R3F_LOG_action_deverrouiller = "Desbloquear ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Objeto bloqueado";