clearWeaponCargoGlobal _this;
clearMagazineCargoGlobal _this;
clearItemCargoGlobal _this;
_this addItemCargoGlobal ["BWA3_G36KA0",5];
_this addItemCargoGlobal ["BWA3_G36KA2",5];
_this addItemCargoGlobal ["BWA3_G36KA3",5];
_this addItemCargoGlobal ["BWA3_G36A1",5];
_this addItemCargoGlobal ["BWA3_G36A2",5];
_this addItemCargoGlobal ["BWA3_G36A3",5];
_this addItemCargoGlobal ["BWA3_G27",5];
_this addItemCargoGlobal ["BWA3_G27_AG40",5];
_this addItemCargoGlobal ["BWA3_MG3",5];
_this addItemCargoGlobal ["BWA3_MG4",5];
_this addItemCargoGlobal ["BWA3_MG5",5];
_this addItemCargoGlobal ["BWA3_G28",5];
_this addItemCargoGlobal ["BWA3_G38C",5];
_this addItemCargoGlobal ["BWA3_G38",5];
_this addItemCargoGlobal ["BWA3_G38K",5];
_this addItemCargoGlobal ["BWA3_G38K_AG40",5];

_this addItemCargoGlobal ["BWA3_G28",5];
_this addItemCargoGlobal ["BWA3_G29",5];
_this addItemCargoGlobal ["BWA3_G82",5];

_this addItemCargoGlobal ["BWA3_G8_Patrol",5];
_this addItemCargoGlobal ["BWA3_G36A1_green",5];
_this addItemCargoGlobal ["BWA3_G36A1_AG40_green",5];
_this addItemCargoGlobal ["BWA3_G36A3_green",5];
_this addItemCargoGlobal ["BWA3_G36KA0_green",5];
_this addItemCargoGlobal ["BWA3_G36KA2_green",5];

_this addItemCargoGlobal ["BWA3_Bunkerfaust_loaded",10];
_this addItemCargoGlobal ["BWA3_Fliegerfaust",20];
_this addItemCargoGlobal ["BWA3_CarlGustav",10];
_this addItemCargoGlobal ["BWA3_PzF3_Tandem_Loaded",10];
_this addItemCargoGlobal ["BWA3_RGW90_Loaded",10];

_this addItemCargoGlobal ["BWA3_15Rnd_9x19_P8",50];
_this addItemCargoGlobal ["BWA3_30Rnd_556x45_G36_Tracer",50];
_this addItemCargoGlobal ["BWA3_20Rnd_762x51_G28_Tracer",50];
_this addItemCargoGlobal ["BWA3_120Rnd_762x51_Tracer",50];
_this addItemCargoGlobal ["BWA3_120_Rnd_762x51_Tracer_soft",50];
_this addItemCargoGlobal ["BWA3_120_Rnd_762x51_Tracer",50];
_this addItemCargoGlobal ["BWA3_200Rnd_556x45_Tracer",50];
_this addItemCargoGlobal ["BWA3_10Rnd_762x51_G28_Tracer",40];
_this addItemCargoGlobal ["BWA3_20Rnd_762x51_G28_Tracer",40];
_this addItemCargoGlobal ["BWA3_10Rnd_86x70_G29_Tracer",40];
_this addItemCargoGlobal ["BWA3_10Rnd_127x99_G82_Tracer",40];
_this addItemCargoGlobal ["BWA3_10Rnd_127x99_G82_AP_Tracer",40];
_this addItemCargoGlobal ["BWA3_10Rnd_127x99_G82_Raufoss_Tracer",40];

_this addItemCargoGlobal ["1Rnd_HE_Grenade_shell",20];
_this addItemCargoGlobal ["1Rnd_Smoke_Grenade_shell",20];
_this addItemCargoGlobal ["1Rnd_SmokeYellow_Grenade_shell",20];
_this addItemCargoGlobal ["1Rnd_SmokeBlue_Grenade_shell",20];
_this addItemCargoGlobal ["1Rnd_SmokeRed_Grenade_shell",20];
_this addItemCargoGlobal ["1Rnd_SmokePurple_Grenade_shell",20];
_this addItemCargoGlobal ["ACE_40mm_Flare_white",20];
_this addItemCargoGlobal ["ACE_40mm_Flare_green",20];
_this addItemCargoGlobal ["ACE_40mm_Flare_red",20];
_this addItemCargoGlobal ["ACE_40mm_Flare_ir",20];
_this addItemCargoGlobal ["UGL_FlareRed_F",20];
_this addItemCargoGlobal ["UGL_FlareGreen_F",20];
_this addItemCargoGlobal ["UGL_FlareWhite_F",20];
_this addItemCargoGlobal ["UGL_FlareCIR_F",20];
_this addItemCargoGlobal ["ACE_HuntIR_M203",10];
        
_this addItemCargoGlobal ["BWA3_PzF3_DM32",20];
_this addItemCargoGlobal ["BWA3_Fliegerfaust_Mag",20];
_this addItemCargoGlobal ["BWA3_CarlGustav_HE",20];
_this addItemCargoGlobal ["BWA3_CarlGustav_HEAT",20];
_this addItemCargoGlobal ["BWA3_CarlGustav_HEDP",20];
_this addItemCargoGlobal ["BWA3_CarlGustav_Smoke",20];
_this addItemCargoGlobal ["BWA3_PzF3_Tandem",20];

_this addItemCargoGlobal ["BWA3_DM51A1",10];
_this addItemCargoGlobal ["ACE_M84",10];
_this addItemCargoGlobal ["BWA3_DM25",10];
_this addItemCargoGlobal ["BWA3_Blue",10];
_this addItemCargoGlobal ["BWA3_Green",10];
_this addItemCargoGlobal ["BWA3_Orange",10];
_this addItemCargoGlobal ["BWA3_Purple",10];
_this addItemCargoGlobal ["BWA3_Red",10];
_this addItemCargoGlobal ["BWA3_Yellow",10];
_this addItemCargoGlobal ["B_IR_Grenade",10];
_this addItemCargoGlobal ["ACE_Chemlight_HiOrange",10];
_this addItemCargoGlobal ["ACE_Chemlight_HiRed",10];
_this addItemCargoGlobal ["ACE_Chemlight_HiYellow",10];
_this addItemCargoGlobal ["ACE_Chemlight_HiWhite",10];
_this addItemCargoGlobal ["ACE_HandFlare_White",10];
_this addItemCargoGlobal ["ACE_HandFlare_Red",10];
_this addItemCargoGlobal ["ACE_HandFlare_Green",10];
_this addItemCargoGlobal ["ACE_HandFlare_Yellow",10];
_this addItemCargoGlobal ["ClaymoreDirectionalMine_Remote_Mag",10];  
_this addItemCargoGlobal ["DemoCharge_Remote_Mag",10];
_this addItemCargoGlobal ["SatchelCharge_Remote_Mag",10];
_this addItemCargoGlobal ["rhs_ec400_mag",10];
        
_this addItemCargoGlobal ["ACE_NVG_Gen4",5];
_this addItemCargoGlobal ["ACE_NVG_Wide",5];
_this addItemCargoGlobal ["ToolKit",5];
_this addItemCargoGlobal ["ACE_TacticalLadder_Pack",5];
_this addItemCargoGlobal ["ACE_VMH3",5];
_this addItemCargoGlobal ["ACE_wirecutter",5];
_this addItemCargoGlobal ["ACE_DefusalKit",5];
_this addItemCargoGlobal ["ACE_ConcertinaWireCoil",5];
_this addItemCargoGlobal ["ACE_TacticalLadder",5];
_this addItemCargoGlobal ["ACE_SpraypaintGreen",5];
_this addItemCargoGlobal ["ACE_Flashlight_XL50",5];
_this addItemCargoGlobal ["ACE_Clacker",5];
_this addItemCargoGlobal ["ACE_EntrenchingTool",5];
_this addItemCargoGlobal ["ACE_MapTools",5];
_this addItemCargoGlobal ["ACE_microDAGR",5];
_this addItemCargoGlobal ["B_UavTerminal",1];
_this addItemCargoGlobal ["BWA3_ItemNaviPad",5];
_this addItemCargoGlobal ["ACE_DAGR",5];
_this addItemCargoGlobal ["ACE_ATragMX",5];
_this addItemCargoGlobal ["ACE_RangeCard",5];
_this addItemCargoGlobal ["ACE_Sandbag_empty",5];
_this addItemCargoGlobal ["ACE_IR_Strobe_Item",5];
_this addItemCargoGlobal ["ACE_HuntIR_monitor",5];
_this addItemCargoGlobal ["ACE_Kestrel4500",5];
_this addItemCargoGlobal ["ACE_RangeTable_82mm",5];
_this addItemCargoGlobal ["ACE_SpottingScope",5];
_this addItemCargoGlobal ["ACE_Tripod",5];
_this addItemCargoGlobal ["ACE_Vector",5];
_this addItemCargoGlobal ["BWA3_Vector",5];
_this addItemCargoGlobal ["ACE_Yardage450",5];
_this addItemCargoGlobal ["ACE_MX2A",5];  
_this addItemCargoGlobal ["ACE_CableTie",5];
_this addItemCargoGlobal ["BWA3_M92_Core_Fleck_Camera",5];
_this addBackpackCargoGlobal ["BWA3_AssaultPack_Fleck",5];
_this addBackpackCargoGlobal ["BWA3_TacticalPack_Fleck",5];
_this addBackpackCargoGlobal ["tfw_ilbe_blade_wd",1];
_this addItemCargoGlobal ["BWA3_G_Combat_black",5];
_this addItemCargoGlobal ["BWA3_G_Combat_orange",5];

_this addItemCargoGlobal["bwa3_optic_pmii_shortdotcc",5];
_this addItemCargoGlobal["bwa3_optic_m5xi_msr",5];
_this addItemCargoGlobal["bwa3_optic_m5xi_msr_microt2",5];
_this addItemCargoGlobal["bwa3_optic_m5xi_tremor3_microt2",5];
_this addItemCargoGlobal["bwa3_optic_hensoldt",5];
_this addItemCargoGlobal["bwa3_optic_compm2",5];
_this addItemCargoGlobal["bwa3_optic_compm_green",5];
_this addItemCargoGlobal["bwa3_optic_microt1",5];
_this addItemCargoGlobal["bwa3_optic_microt2",5];
_this addItemCargoGlobal["bwa3_optic_eotech552",5];
_this addItemCargoGlobal["bwa3_optic_eotech552_green",5];
_this addItemCargoGlobal["bwa3_optic_eotech",5];
_this addItemCargoGlobal["bwa3_optic_eotech_mag_off",5];
_this addItemCargoGlobal["bwa3_optic_rsas_green",5];
_this addItemCargoGlobal["bwa3_optic_zo4x30",5];
_this addItemCargoGlobal["bwa3_optic_zo4x30_microt2",5];
_this addItemCargoGlobal["bwa3_optic_zo4x30_rsas",5]; 
_this addItemCargoGlobal["bwa3_optic_zo4x30i",5];
_this addItemCargoGlobal["bwa3_optic_zo4x30i_microt2",5];
_this addItemCargoGlobal["bwa3_optic_zo4x30i_rsas",5];
_this addItemCargoGlobal["bwa3_acc_varioray_irlaser_black",5];
_this addItemCargoGlobal["bwa3_acc_llm01_irlaser",5];
_this addItemCargoGlobal["bwa3_acc_llm01_irlaser_green",5];
_this addItemCargoGlobal["bwa3_acc_llm01_irlaser_underbarrel",5];
_this addItemCargoGlobal["bwa3_muzzle_snds_rotex_iia",5];
_this addItemCargoGlobal["bwa3_muzzle_snds_qdss",5];
_this addItemCargoGlobal["bwa3_muzzle_snds_qdss_green",5];
_this addItemCargoGlobal["bwa3_muzzle_snds_rotex_iic_green",5];
_this addItemCargoGlobal["bwa3_muzzle_snds_rotex_monoblock",5];
_this addItemCargoGlobal["bwa3_bipod_harris",5];
_this addItemCargoGlobal["bwa3_bipod_harris_green",5];
_this addItemCargoGlobal["bwa3_bipod_atlas",5];
_this addItemCargoGlobal["bwa3_bipod_mg3",5];
_this addItemCargoGlobal["bwa3_optic_nsa80",5];
_this addItemCargoGlobal["bwa3_optic_carlgustav",5];
_this addItemCargoGlobal["bwa3_optic_IRV600",5];
_this addItemCargoGlobal["bwa3_optic_NSV600",5];
_this addItemCargoGlobal["bwa3_optic_NSV80",5];